_BASE_: 'option2b_observed_visible_nodes_pair_geometry.yaml'

DATASETS:
  TRAIN: ("mem_option2b_observed_visible_nodes_pair_geometry_zero_map",)
  TEST: ("mem_option2b_observed_visible_nodes_pair_geometry_zero_map",)

MODEL:
  MEM_GRAPH:
    ZERO_MAP_NODE_FEATURES: True
